set up GitHub Actions to have a simple cI system
hirooih/perl-trg pull request #2
Opened 2021-02-24 17:34 UTC by szabgab

2021-02-25 14:57 UTC, hirooih commented
@szabgab 
Thank you. 
I just migrated this repository from SourceForge. to GitHub last weekend.  This is my first original repository on GitHub. I am not familiar with Docker, either. I have been at a loss by seeing a lot of documents on https://docs.github.com/en/actions.

Your PR is a great clue for me. Give me some time to understand your `ci.yml`. 
The most important thing I learned was knowning that I could run `apt-get` to install GNU Readline Library.
And it seems that I can use `brew `command on macOS.

> https://github.com/k6io/example-github-actions/blob/master/.github/workflows/macos.yml

Let me ask you some questions.

***

What is the difference between two containers you used, `perldocker/perl-tester` and `perl`?
Could you give the pointer to `perl` container as https://hub.docker.com/r/perldocker/perl-tester for `perldocker/perl-tester`?

***

I don't think we need the following lines;

```
  schedule:
    - cron: '42 5 * * *'
```

Am I correct?

***

Do we need to add `workflow_dispatch` to test a workflow manually?

Thanks in advance.

2021-02-25 15:30 UTC, szabgab commented
Recently I was trying various ways to install Term::ReadLine::Gnu because it was a dependency of one of the modules I was testing. You can see the results here: https://github.com/szabgab/testing-Term-ReadLine-Gnu/
Feel free to pick up anything from there.

I set up an extensive CI system for Test::Class that you can see here: https://github.com/szabgab/test-class
There is some explanation in the yaml file (including why I have the scheduled job), but if you have time you might even want to watch the video where I explain the whole thing:  https://perlmaven.com/github-actions-ci-job-for-test-class

I don't know if  https://hub.docker.com/r/perldocker/perl-tester as a full link would work, but  https://hub.docker.com/ is the default location to look for images. The full URL might also work. Why would you want it?

You need workflow_dispatch if you'd like to trigger the job manually and not just using push.

2021-02-25 15:34 UTC, szabgab commented
For our purposes on GitHub Actions a Docker image is just a VM with some stuff already installed, but you can use the regular apt/yum commands that are appropriate for the packaging system of the distribution that was used to create the image.

2021-02-25 16:55 UTC, hirooih commented
Thank you for your reply.  I will check links you provided.

2021-02-28 06:10 UTC, hirooih commented on .github/workflows/ci.yml
> +    - cron: '42 5 * * *'
Remove these lines.

I read your comments on https://github.com/szabgab/test-class/blob/master/.github/workflows/ci.yml and watch your video https://perlmaven.com/github-actions-ci-job-for-test-class.

cpantesters covers the issue for CPAN modules.

2021-02-28 06:10 UTC, hirooih commented on .github/workflows/ci.yml
> +            make test
Remove this job.

Term::ReadLine::Gnu uses only standard modules for portability.  We don't need perldocker/perl-tester.

2021-02-28 06:10 UTC, hirooih commented on .github/workflows/ci.yml
> +      image: perl:${{ matrix.perl-version }}
Add a comment of this image, for example '# https://hub.docker.com/_/perl'.

Do they support '5.20'?  It seems that only '5.28', '5.30', and '5.32' are supported.

2021-02-28 06:12 UTC, hirooih requested changes
Thank you for your PR. This is what I was looking for.  I am studying GitHub Actions. Tips you gave me help me a lot.

I would like to ask you to make this workflow simple as far as possible as I commented.

I want to use GitHub Actions to check a wrong commit.
[cpantesters](http://matrix.cpantesters.org/?dist=Term-ReadLine-Gnu+1.40) test my module periodically on various Perl versions. We don't have do same things here.

Thanks.

2021-02-28 06:12 UTC, closed without merging

2021-02-28 06:13 UTC, szabgab commented
I don't think you are right, but I am sure you can now create your own configuration.

2021-02-28 09:38 UTC, hirooih commented
> I don't think you are right, but I am sure you can now create your own configuration.

I see.
I will create my configuration based on your PR.

Again, thank you for your valuable advices.